### ISSUE TITLE
很高兴认识与交流

### ISSUE THREAD

**Issue by PhilosopherZ** [bugsuse/papers#1]
看了你的博客与GitHub，很高兴认识与交流知识。

**Comment by bugsuse** [comment]
欢迎欢迎

**Comment by bugsuse** [comment]
欢迎欢迎 @PhilosopherZ

**Comment by PhilosopherZ** [comment]
@bugsuse 能方便留个邮箱交流一些问题吗？比如机器学习之类的。我的邮箱是zhangzhe@mail.iap.ac.cn

**Comment by bugsuse** [comment]
libravo@foxmail.com，我现在主要是做空气质量预报和数据同化的内容，对于机器学习涉及比较少 @PhilosopherZ

**Comment by PhilosopherZ** [comment]
嗯嗯，可以互相学习进步。你今年刚毕业，我看你本科论文是做闪电的？现在在哪里读研吗？我在大气所，大气边界层方向。 @bugsuse

**Comment by bugsuse** [comment]
我硕士已经毕业了😂 @PhilosopherZ

**Comment by PhilosopherZ** [comment]
嗯嗯，那你是前辈师兄了，多多指教。

**Comment by bugsuse** [comment]
谈不上指教😂，可以多交流
